# Generated by Django 4.2.2 on 2023-11-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.CharField(default='DSA', max_length=50),
        ),
    ]
